config/routes.rb
Twitter::Application.routes.draw do
  root to: 'home#index'

  resource :user, only: [:new, :create, :edit, :update] do
    get :mentions
  end

  resource :session, only: [:new, :create, :destroy]
  resources :tweets, only: [:index, :new, :create, :show, :destroy]
  resources :users, only: :show, as: :timeline
end

app/models/mention.rb
class Mention < ActiveRecord::Base
  attr_accessible :tweet, :user
  belongs_to :tweet
  belongs_to :user

  validate :tweet, presence: true
  validate :user, presence: true
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
  has_many :mentions, dependent: :destroy
  has_many :mentioned_users, through: :mentions, source: :user
  attr_accessible :content

  validates :user, presence: true
  validates :content, length: {in: 1..160}

  before_create :create_mentions

  # http://stackoverflow.com/questions/7520297/regex-to-parse-user-mentions
  MENTION_REGEX = /(?:^|\s)\@(\w*[a-zA-Z_]+\w*)/

  def create_mentions
    content.scan(MENTION_REGEX).each do |name|
      mentioned_user = User.find_by_name(name)

      if mentioned_user.present?
        mentions.build(user: mentioned_user)
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :tweets
  has_many :mentions
  has_many :received_tweets, through: :mentions, source: :tweet

  attr_accessible :name,
                  :password_digest,
                  :password

  validates :password_digest, presence: true, allow_blank: false
  validates :password, presence: true

  validates :name, presence: true,
                   uniqueness: true,
                   format: {
                     with: /^[[:alnum:]]+$/,
                     message: 'Only letters and numbers allowed.'
                   },
                   allow_blank: false

  def self.authenticate(name, password)
    find_by_name(name).try(:authenticate, password)
  end

  def to_s
    name
  end

  def to_param
    name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

  # Sessions

  def logged_in?
    session[:current_user_id].present?
  end

  helper_method :logged_in?

  def current_user
    if session[:current_user_id]
      User.find(session[:current_user_id])
    else
      nil
    end
  end

  helper_method :current_user

  def require_session
    unless logged_in?
      redirect_to new_session_path
    end
  end

  def not_found
    raise ActionController::RoutingError.new('Not Found')
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @tweets = Tweet.order('created_at DESC').page params[:page]

    if logged_in?
      @mentions = current_user.received_tweets.order('created_at DESC').limit(5)
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  layout 'menuless'

  def create
    if logged_in?
      destroy
      return
    end

    user = User.authenticate(*session_params.values_at(:name, :password))

    if user.present?
      session[:current_user_id] = user.id
      flash[:notice] = "Welcome back, #{user.name}"
      redirect_to root_path

    else
      flash[:alert] = 'Wrong username/password combination.'
      render :new
    end
  end

  def destroy
    reset_session
    flash[:notice] = 'You have been logged out successfully.'
    redirect_to new_session_path
  end

  private

  def session_params
    params.permit(:name, :password)
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_filter :require_session, only: [:new, :create, :destroy]
  before_filter :set_tweet, only: [:show, :edit, :update, :destroy]

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user = current_user

    if @tweet.save
      flash[:notice] = 'Your tweet has been successfully published!'
      redirect_to @tweet
    else
      render :new
    end
  end

  def destroy
    if @tweet.destroy
      flash[:alert] = 'Your tweet has been deleted.'
      redirect_to timeline_path(current_user)
    else
      flash[:error] = 'Error deleting your tweet.'
      render 'show'
    end
  end

  def index
    @tweets = Tweet.order('created_at DESC').page params[:page]
  end

  private

  def tweet_params
    params.require(:tweet).permit(:content)
  end

  def set_tweet
    @tweet = Tweet.find(params[:id])

    unless @tweet
      redirect_to tweets_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_session, only: [:edit, :update, :mentions]
  before_filter :require_sessionless, only: [:new, :create]

  layout 'menuless', only: :new

  def new
    @user = User.new
  end

  def create
    @user = User.new(create_params)

    if @user.save
      flash[:notice] = 'User was successfully created.'
      redirect_to edit_user_path
    else
      render :new
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user

    if @user.update_attributes(update_params)
      flash[:notice] = 'Your settings have been updated.'
      redirect_to edit_user_path
    else
      render :edit
    end
  end

  def show
    @user = User.find_by_name(params[:id])

    if @user.blank?
      not_found
    end

    @tweets = @user.tweets.order('created_at DESC').page params[:page]
  end

  def mentions
    @mentions = current_user.received_tweets.page params[:page]
  end

  private

  def update_params
    params.require(:user).permit(:password)
  end

  def create_params
    params.require(:user).permit(:name, :password)
  end

  def require_sessionless
    if logged_in?
      redirect_to edit_user_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.haml
%p Hello, you're home.

app/views/home/index.html.haml
- if @mentions.present?
  = render partial: 'tweets/mentions', object: @mentions

= render template: 'tweets/index'

app/views/layouts/application.haml
!!!
%html
  %head
    %title Twitter
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags

= yield

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Twitter
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags

.container
  .row
    .span8
      %h1.row.span8= link_to 'Twitter', root_path
      .row.span8= render 'shared/alerts'
      #main.row.span8= yield

    .span4
      - unless local_assigns[:menuless]
        .row.span4= render 'shared/menu'

      #sidebar.row.span4
        - if content_for?(:sidebar)
          = yield :sidebar
        - elsif logged_in?
          = render 'tweets/form', tweet: Tweet.new

  .span12
    = render 'shared/footer'

app/views/layouts/menuless.html.haml
= render template: 'layouts/application', locals: {menuless: true}

app/views/shared/_alerts.html.haml
- if flash[:notice] || local_assigns[:notice]
  .alert.alert-success= flash[:notice] || local_assigns[:notice]

- if flash[:alert] || local_assigns[:alert]
  .alert.alert-error= flash[:alert] || local_assigns[:alert]

app/views/shared/_footer.html.haml
%p.footer
  No rights reserved 2013!

app/views/shared/_menu.html.haml
#menu
  - if logged_in?
    .btn-group
      = link_to '#', class: 'btn btn-primary' do
        %i.icon-user.icon-white
        = current_user

      = link_to '#', data: {toggle: 'dropdown'}, class: 'btn btn-primary dropdown-toggle' do
        %span.caret

      %ul.dropdown-menu
        %li
          = link_to timeline_path(current_user) do
            %i.icon-tasks
            Timeline

        %li
          = link_to mentions_user_path do
            %i.icon-thumbs-up
            Your mentions

        %li
          = link_to edit_user_path do
            %i.icon-wrench
            Settings

    .btn-group
      %li= button_to 'Logout', session_path, method: :delete, class: 'btn btn-danger logout', confirm: 'Are you sure you want to logout?'

  - else
    = render 'sessions/form'

app/views/tweets/_form.html.haml
%h4
  Post a new tweet!
  %i.icon-comment

= form_for tweet do |f|
  - if tweet.errors.any?
    #error_explanation
      %h2= "#{pluralize(tweet.errors.count, "error")} prevented this tweet from being saved:"
      %ul
        - tweet.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :content
    = f.text_area :content
  .actions
    = f.submit 'Tweet!', class: 'btn btn-success'

app/views/tweets/_mentions.html.haml
.mentioned-tweets
  %h4
    Your mentions
    = link_to '(See all)', mentions_user_path, class: 'btn btn-link'
  = (render mentions) || 'It looks like you don\'t have any mentions yet.'

app/views/tweets/_tweet.html.haml
.row
  .tweet.span8
    %h5.author
      = link_to tweet.user, timeline_path(tweet.user)
      says:
    %p.content= tweet.content

    .details
      %small.timestamp.pull-left
        = "#{time_ago_in_words(tweet.created_at)} ago"

      - if tweet.user == current_user
        = button_to 'Delete', tweet_path(tweet), method: :delete, confirm: 'Are you sure you want to delete this tweet?', class: 'btn btn-danger btn-mini pull-left'

      = link_to tweet, class: 'permalink btn btn-link btn-mini pull-left' do
        permalink
        %i.icon-chevron-right

    .clearfix

app/views/tweets/edit.html.haml
%h4 Editing tweet

= render 'form'

app/views/tweets/index.html.haml
%h4 All tweets by everyone!

= render @tweets || 'Nobody has tweeted yet!'
= paginate @tweets

app/views/tweets/new.html.haml
= render 'form', tweet: @tweet

- content_for :sidebar do
  %p The maximum length for a tweet is 140 characters.

app/views/tweets/show.html.haml
= render @tweet

- if @tweet.mentions.any?
  .mentions
    %h5
      %i.icon-user
      This tweet mentioned:

    %ul.unstyled
      - @tweet.mentioned_users.each do |user|
        %li
          = link_to user, timeline_path(user), class: 'btn btn-link'

app/views/users/_create_form.html.haml
= form_for @user, url: user_path do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :password
    = f.password_field :password
  .actions
    = f.submit 'Create account', class: 'btn btn-primary'

  = link_to 'Login', new_session_path, class: 'btn'

app/views/users/_form.html.haml
= form_for @user, url: user_path do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :password
    = f.password_field :password
  .actions
    = f.submit @user.persisted? ? 'Update' : 'Register'

app/views/users/_update_form.html.haml
= form_for @user, url: user_path do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name, disabled: 'disabled'
  .field
    = f.label :password
    = f.password_field :password
  .actions
    = f.submit 'Update', class: 'btn btn-primary'

app/views/users/edit.html.haml
%h4= "Editing settings for #{@user}"

= render 'update_form'

app/views/users/mentions.html.haml
= render partial: 'tweets/mentions', object: @mentions
= paginate @mentions

app/views/users/new.html.haml
%h4 Create a new account

= render 'create_form'

app/views/users/show.html.haml
%h4= "#{@user}'s timeline"

= render @tweets || "#{@user} has no tweets yet."
= paginate @tweets